---
- name: This is a playbook to execute roles
  hosts: linux
  roles:
   - package_remove
   - package_install
   - patching
   - profile_mgmt
   - timezone
   - syslog_updates


     
  